const quizzes = [
    {
      course: "RS101",
      _id:"1",
      title: "Q1-HTML",
      type: "Graded Quiz", 
      point: 10, 
      assignmentGroup: "Quizzes", 
      question_nums:"10",
      shuffleAnswers: true, 
      timeLimit: true,
      timeAllowed:10, 
      multipleAttempts: false,
      attemptsAllowed: 1, 
      showCorrectAnswers: {
        show: false, 
        when: null, 
      },
      accessCode: "", 
      oneQuestionAtATime: true, 
      webcamRequired: false, 
      lockQuestionsAfterAnswering: false, 
      dueDate: "2024-12-10T21:00:00", 
      availableFromDate: "2024-12-01T21:00:00", 
      untilDate: "2024-12-10T21:00:00", 
      publish: false,
      description:"",
    },
    {
      course: "RS101",
      _id:"2",
      title: "Q2-CSS",
      type: "Practice Quiz",
      question_nums:"20",
      point: 0, 
      assignmentGroup: "Assignments",
      shuffleAnswers: false,
      timeLimit: 0,
      timeAllowed:10, 
      multipleAttempts: true,
      attemptsAllowed: 3, 
      showCorrectAnswers: {
        show: true,
        when: "Immediately", 
      },
      accessCode: "QUIZ123",
      oneQuestionAtATime: false,
      webcamRequired: true,
      lockQuestionsAfterAnswering: true,
      viewResults: true,
      dueDate: "2024-12-20T21:00:00",
      availableFromDate: "2024-12-05T21:00:00",
      untilDate: "2024-12-20T21:00:00",
      publish: false,
      description:"",
    },
    {
      course: "RS101",
      _id:"3",
      title: "Q3-test",
      type: "Graded Quiz", 
      point: 10, 
      assignmentGroup: "Quizzes", 
      question_nums:"10",
      shuffleAnswers: true, 
      timeLimit: 20, 
      timeAllowed:10, 
      multipleAttempts: false,
      attemptsAllowed: 1, 
      showCorrectAnswers: {
        show: false, 
        when: null, 
      },
      accessCode: "", 
      oneQuestionAtATime: true, 
      webcamRequired: false, 
      lockQuestionsAfterAnswering: false, 
      viewResults: true,
      dueDate: "2024-11-10T21:00:00", 
      availableFromDate: "2024-11-01T21:00:00", 
      untilDate: "2024-11-10T21:00:00", 
      publish: false,
      description:"",
    },
  ];
  
  export default quizzes;
  